---
abstract: 'Implements symbolic and ls chmod modes'
author:
  - 'Jeff Pinyan <japhy.734+CPAN@gmail.com>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-chmod
no_index:
  file:
    - perlcritic.rc
provides:
  File::chmod:
    file: lib/File/chmod.pm
    version: 0.35
requires:
  Carp: 0
  Exporter: 0
  base: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/file-chmod/issues
  homepage: https://metacpan.org/dist/File-chmod
  repository: git://github.com/xenoterracide/file-chmod.git
version: 0.35
x_contributors:
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
